# fly.toml file generated for atc-info on 2022-11-22T21:34:58+09:00

app = "atc-info"
kill_signal = "SIGINT"
kill_timeout = 25
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

